# docker-compose.yml for Syndicate CI testing

version: '2'

services:

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: syndicate-ci-test
    depends_on:
      - ms
    links:
      - ms
    volumes:
      - ./ms:/opt/ms:ro
      - ../testwrapper.sh:/opt/testwrapper.sh:ro
      - ../testrunner.py:/opt/testrunner.py:ro
      - ../config.sh:/opt/config.sh:ro
      - ../syndicate-tests:/opt/syndicate-tests:ro
      - ../results:/opt/results
      - ../output:/opt/output
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN
    privileged: true


  ms:
    build:
      context: .
      dockerfile: Dockerfile.ms
    image: syndicate-ci-ms
    expose:
      - "8080"
    volumes:
      - ./ms:/opt/ms:ro
      - ./ms/app.yaml:/usr/src/syndicate/ms/app.yaml:ro
