# Syndicate CI Test Dockerfile

FROM syndicate-ci-base
MAINTAINER Zack Williams <zdw@cs.arizona.edu>

# Install Syndicate UG tools
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y --force-yes\
    build-essential \
    curl \
    fuse \
    graphviz \
    python-pip \
    python-psutil \
    python-yaml \
    syndicate-ag \
    syndicate-rg \
    syndicate-ug-tools \
    syndicatefs \
    valgrind

# Install Node.js
RUN curl -sL https://deb.nodesource.com/setup_4.x | bash - && \
    apt-get install -y nodejs

# Install Syndicate Node.js binding
RUN npm install -g \
    syndicate-drive \
    syndicate-drive-ug-tools

# Install fstest
COPY fstest /opt/fstest
WORKDIR /opt/fstest
RUN make && cp fstest /usr/bin/ && chmod 777 /usr/bin/fstest

# Install additional python tools/modules
RUN pip install gprof2dot python-magic

# Join to the fuse group
RUN usermod -aG fuse syndicate

# Switch to being the syndicate user
USER syndicate

# Switch to /opt
WORKDIR /opt

# Run the tests
CMD [ "/bin/bash" ]
