# Syndicate CI Test Dockerfile

FROM syndicate-ci-base
MAINTAINER Zack Williams <zdw@cs.arizona.edu>

# Install Syndicate UG tools
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y --force-yes\
    python-yaml \
    python-psutil \
    syndicate-ug-tools \
    syndicate-rg \
    syndicate-ag \
    syndicatefs \
    build-essential \
    fuse \
    valgrind

# Install fstest
COPY fstest /opt/fstest
WORKDIR /opt/fstest
RUN make && cp fstest /usr/bin/ && chmod 777 /usr/bin/fstest

# Join to the fuse group
RUN usermod -aG fuse syndicate

# Switch to being the syndicate user
USER syndicate

# Switch to /opt
WORKDIR /opt

# Run the tests
CMD [ "/bin/bash" ]
